import Image from "next/image";
import Link from "next/link";
import { AppointmentCTA } from "@/components/appointment-cta";
import { JsonLd } from "@/components/json-ld";
import { siteConfig } from "@/lib/site-config";

const treatments = [
  { n: "01", title: "Ortodoncia", text: "Evaluación y planificación para acompañar la función, alineación y armonía de tu sonrisa.", href: "/ortodoncia" },
  { n: "02", title: "Alineadores dentales", text: "Una alternativa removible y discreta, indicada después de una valoración profesional.", href: "/alineadores-dentales" },
  { n: "03", title: "Brackets", text: "Un tratamiento de ortodoncia preciso, con seguimiento periódico y un plan individual.", href: "/brackets" },
];

export default function Home() {
  const schema = { "@context": "https://schema.org", "@type": "WebSite", name: siteConfig.name, url: siteConfig.url, description: siteConfig.description };
  return <main><JsonLd data={schema} />
    <section className="hero"><div className="hero-arc" aria-hidden="true" /><div className="shell hero-grid"><div className="hero-copy"><span className="eyebrow">DRA. CATALINA OVARES · COSTA RICA</span><h1>Ortodoncia que se adapta a <em>tu sonrisa.</em></h1><p>Atención especializada en ortodoncia, alineadores dentales y brackets, con un plan pensado para cada persona.</p><div className="button-row"><a className="button" href={siteConfig.appointment} target="_blank" rel="noreferrer">Agendar valoración</a><Link className="text-link" href="/alineadores-dentales">Conocer tratamientos <span aria-hidden="true">→</span></Link></div><div className="hero-note"><span className="star" aria-hidden="true">✦</span><p><b>Escaneo, valoración y diseño.</b><br />El primer paso para comprender tu caso.</p></div></div><div className="hero-portrait"><Image src={siteConfig.doctorImage} alt="Dra. Catalina Ovares, especialista en ortodoncia y alineadores dentales" width={1254} height={1254} priority sizes="(max-width: 760px) 100vw, 48vw" /></div></div></section>
    <section className="intro-section shell"><div className="section-number">01</div><div className="intro-heading"><span className="eyebrow">UNA ATENCIÓN CERCANA</span><h2>Tu sonrisa merece un plan propio.</h2></div><div className="intro-copy"><p>La ortodoncia no comienza con un aparato: comienza al escuchar lo que deseas, estudiar tu sonrisa y explicar las opciones con claridad.</p><Link className="text-link" href="/dra-catalina-ovares">Conocer a Catalina <span aria-hidden="true">→</span></Link></div></section>
    <section className="treatments-section"><div className="shell"><span className="eyebrow">TRATAMIENTOS</span><div className="split-title"><h2>Opciones para sonreír con confianza.</h2><p>Cada tratamiento requiere una valoración individual. Juntos podemos elegir un camino acorde con tus necesidades y estilo de vida.</p></div><div className="treatment-list">{treatments.map((item) => <article key={item.href}><span>{item.n}</span><h3>{item.title}</h3><p>{item.text}</p><Link href={item.href} aria-label={`Conocer más sobre ${item.title}`}>Ver tratamiento <b aria-hidden="true">↗</b></Link></article>)}</div></div></section>
    <section className="aligner-story shell"><div className="aligner-art" aria-hidden="true"><span>OVARES</span><b>ALINEADORES</b><i>✦</i></div><div className="aligner-copy"><span className="eyebrow">ORTODONCIA DISCRETA</span><h2>Una opción que acompaña tu rutina.</h2><p>Los alineadores transparentes son removibles y se planifican digitalmente. Su uso y seguimiento deben adaptarse a las indicaciones de cada caso.</p><div className="brand-links"><Link href="/invisalign">Invisalign</Link><Link href="/spark">SPARK</Link><Link href="/smartee">SMARTEE</Link></div><Link className="button button-outline" href="/alineadores-dentales">Explorar alineadores</Link></div></section>
    <section className="process-section"><div className="shell"><span className="eyebrow">TU PRIMERA VALORACIÓN</span><h2>Tres pasos para comenzar.</h2><div className="process-line"><article><b>01</b><h3>Escaneo</h3><p>Analizamos tu sonrisa con tecnología digital.</p></article><article><b>02</b><h3>Valoración</h3><p>Revisamos tu caso y resolvemos tus dudas.</p></article><article><b>03</b><h3>Diseño</h3><p>Definimos un plan personalizado para vos.</p></article></div></div></section>
    <section className="faq-preview shell"><div><span className="eyebrow">PREGUNTAS FRECUENTES</span><h2>Información clara antes de decidir.</h2></div><div><details><summary>¿Cómo sé si puedo usar alineadores?</summary><p>La indicación depende de una valoración clínica individual y de los objetivos del tratamiento.</p></details><details><summary>¿Qué ocurre en la primera valoración?</summary><p>Se revisa tu sonrisa, se conversa sobre tus necesidades y se explican posibles alternativas. El proceso exacto puede variar según cada caso.</p></details><Link className="text-link" href="/preguntas-frecuentes">Ver todas las preguntas <span aria-hidden="true">→</span></Link></div></section>
    <AppointmentCTA />
  </main>;
}
